services:
  ping_pong:
    image: "darnahsan/ping_pong"
    container_name: "ping_pong"
    environment:
      - FIREWORKS_PING_EMBEDDING_API=https://api.fireworks.ai/inference/v1/embeddings
      - FIREWORKS_PING_CHAT_API=https://api.fireworks.ai/inference/v1/chat/completions
      - FIREWORKS_PING_API_KEY=123456
      - FIREWORKS_PONG_EMBEDDING_API=https://api.fireworks.ai/inference/v1/embeddings
      - FIREWORKS_PONG_CHAT_API=https://api.fireworks.ai/inference/v1/chat/completions
      - FIREWORKS_PONG_API_KEY=654321
    ports:
      - "4001:4001"
